# Generated by Django 4.2.9 on 2024-02-05 08:11

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='properties',
            field=models.JSONField(blank=True, default=dict, validators=[product.models.validate_unique_keys]),
        ),
    ]
