# Generated by Django 4.2.9 on 2024-02-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_cartitem_unique_cart_product'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product',
        ),
    ]
