# Generated by Django 4.2.9 on 2024-02-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_cartitem_unique_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
    ]
